Adding Unicode support
JochenKalmbach/StackWalker pull request #35
Opened 2019-03-04 19:12 UTC by OfekShilon

In response to both my need and a reported issue.

2021-04-13 15:13 UTC, SirLynix commented
@JochenKalmbach Do you plan to merge this PR sometimes? I can make a new one if this one is too outdated, having Unicode support would be a plus for this library 😃

2021-04-13 15:26 UTC, emmenlau commented
> @JochenKalmbach Do you plan to merge this PR sometimes? I can make a new one if this one is too outdated, having Unicode support would be a plus for this library

Yes, Unicode support would be great!

2021-04-18 14:30 UTC, JochenKalmbach commented
Currentl the main problem is that you removed several defined which are needed for VC6... so I am not sure if this is ok or not...
Also the definition of DBGHELP_TRANSLATE_TCHAR should be depended on the SDK version...

2021-04-18 16:46 UTC, OfekShilon commented
@JochenKalmbach  This PR was made almost exactly 2 years ago - I'm currently working only on linux and would have a hard time going back to this. Feel free to modify it in any way you see fit.

2022-12-10 18:55 UTC, remittor commented
Fork with fully Unicode support: https://github.com/remittor/StackWalker

2022-12-10 18:56 UTC, equalman commented
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2024-07-27 14:02 UTC, luzpaz commented
bump

2024-07-27 16:39 UTC, JochenKalmbach requested changes
I do not think that we can merge this PR... we can think about a version which has a different filen ame like "stackwalker-tchar.*" which then only supports newer compilers.
Be aware that dbghelp.dll was initially not designed for unicode... so this functions are not availble in older OS versions... also it is not available in older compilers (MS VS++)...

2024-07-27 16:39 UTC, JochenKalmbach commented on Main/StackWalker/StackWalker.cpp
> -#if _MSC_VER >= 1300
This will remove the support of older compilers... there is no need to remove this...

2024-07-27 16:39 UTC, JochenKalmbach commented on Main/StackWalker/StackWalker.cpp
> -#if _MSC_VER < 1400
This would remove support for older compilers...

2024-07-27 16:39 UTC, JochenKalmbach commented on Main/StackWalker/StackWalker.cpp
> -// inline the important dbghelp.h-declarations...
This would remove support for older compilers/Windows SDKs...

2024-07-29 19:23 UTC, JochenKalmbach commented
As said... for older OSes/SDKs there was NO Unicode-version of dbghelp.dll available... so changing this now would break the execution of this on such systems, because it would now assume that a wchar_t version would be there... (if the programis compßiler with unicode)...

2024-07-29 19:23 UTC, closed without merging

2024-07-29 20:02 UTC, SirLynix commented
How about dropping support for the 20th century?

Like seriously, admitting there are still a relevant number of computers running on Windows 95 and depending on this library today, why not embrace the "future"? VC 8.0 got out almost **twenty years ago**.

Make a "legacy" branch to be able to bring back fixes if required (let's recall there hasn't been any commit for more than two years until recently) and add unicode on the master branch.

2024-07-29 22:20 UTC, luzpaz commented
+1 for legacy branch

2024-07-30 05:16 UTC, remittor commented
> for older OSes/SDKs there was NO Unicode-version of dbghelp.dll available... so changing this now would break the execution of this on such systems, because it would now assume that a wchar_t version would be there... (if the programis compßiler with unicode)...

I solved this problem this way:
https://github.com/remittor/StackWalker/blob/44931fec8e985ef4720e722f5f4bc4ccce2b54c5/src/StackWalker.cpp#L741-L755

```
#if !defined(STKWLK_ANSI) && API_VERSION_NUMBER < 11
#error "For Unicode support required update the Windows Platform SDK to v6.0 or later"
#endif
```

> Make a "legacy" branch to be able to bring back fixes if required (let's recall there hasn't been any commit for more than two years until recently) and add unicode on the master branch.

My fork https://github.com/remittor/StackWalker support WinXP and VC6 compiler (Win9X not support).